### ISSUE TITLE
Can't copy password

### ISSUE THREAD

**Issue by Gleek** [ifosch/keepass-mode#2]
On pressing `c` for `keepass-mode-copy-password` on a key entry, I get 'PROTECTED' in my kill ring, instead of the actual password.

Keepass-mode version(melpa): `20200216.723`
Emacs version:
`GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-07-24`

**Comment by ifosch** [comment]
@Gleek, first of all, sorry for the late reply. Looks like there are some changes in keepassxc-cli latest version. I'll look into solutions to this ASAP.

**Comment by ifosch** [comment]
I just fixed this, IIRC MELPA will catch this sooner or later updating their build.
