### ISSUE TITLE
Fail to copy password

### ISSUE THREAD

**Issue by ykgoon** [ifosch/keepass-mode#8]
Hitting `c` results in this error:

```
menu-bar-update-yank-menu: Wrong type argument: stringp, nil
```

**Comment by ykgoon** [comment]
This failed when I first installed the package straight from MELPA.

Maybe MELPA has a lagging version, I installed straight from Github and `c` doesn't throw error.

However it doesn't copy password to kill-ring. Turn out my copy of `keepassxc-cli` doesn't do `show -s`, so the output of password retrieval is `Unknown option 's'.`.

My `keepassxc-cli` version is 2.4.3, looks like it's too old. What version the minimum version this package is designed for?

**Comment by ykgoon** [comment]
Just upgraded to version 2.6.x, it's now working fine.

Documentation should probably cite the minimum required version.

**Comment by ifosch** [comment]
Thanks for notifying. I've added the keepassxc-cli minimum required version in the README.
