### ISSUE TITLE
Cannot enter a group

### ISSUE THREAD

**Issue by ykgoon** [ifosch/keepass-mode#9]
`kdbx` can be opened, groups are displayed.

But upon pressing `enter` we stay on the same page. No entries are seen.

I'm on emacs version 28.0.50, that probably is a big factor.

**Comment by ifosch** [comment]
I am also using 28.0.50 and this works well for me for all files I have at hand.
What's the name of the folder? I had a problem during early development with folders and entries with unexpected characters. Try to rename the folder using KeepassXC, and retry. Of course, I recommend using a copy.

Have you tried to open this file and take a look into this folder with `keepassxc-cli`?
Have you tried with another file and keepass-mode and is still happening?

**Comment by ykgoon** [comment]
> What's the name of the folder? I had a problem during early development with folders and entries with unexpected characters. Try to rename the folder using KeepassXC, and retry. Of course, I recommend using a copy.

Dir name is normal, no spaces or special char.

> Have you tried to open this file and take a look into this folder with `keepassxc-cli`?

Tried this, no problem.

> Have you tried with another file and keepass-mode and is still happening?

It's my one and only file.

This problem only started last week. Nothing else changed except emacs version, which is updated almost daily.

**Comment by ifosch** [comment]
It's weird it started last week. The only thing changed since January is a documentation change. Might it be related to a keepassxc-cli update happening last week? Which versions are you using of keepassxc and keepass-mode?
One approach to be able to reproduce would be you share a copy of this file, with passwords changed or removed, so I can try on my setup.

**Comment by ykgoon** [comment]
My versions:
- keepassxc-cli 2.6.4
- keepass-mode 20210125.301

Here's a newly created kdbx file, problem is reproduced on my end. Password is `1234`.

[test.zip](https://github.com/ifosch/keepass-mode/files/6531099/test.zip)

**Comment by ifosch** [comment]
I couldn't reproduce on my end, i.e. I open it ok. I'm using keepassxc-cli 2.6.2 and latest keepass-mode 20210110.630.
I don't think keepassxc-cli version difference is doing a lot. Instead, I don't know how you got this keepass-mode version, which doesn't seem to exist anywhere on melpa. How did you installed keepass-mode?

**Comment by ykgoon** [comment]
Thanks for checking @ifosch. I'm on Spacemacs, this is how it's installed.
```
     (keepass-mode :location (recipe
                              :fetcher github
                              :repo "ifosch/keepass-mode"))
```

**Comment by ifosch** [comment]
What's the last commit for your keepass-mode install? Also, could you try to recompile all ELisp code?

The other possible reason is something pretty different between keepassxc-cli 2.6.2 and 2.6.4. Looks like they didn't released a deb package for 2.6.4, so maybe you can look into downgrading your keepassxc-cli to 2.6.2. This would validate the problem is not in the emacs side.

**Comment by ykgoon** [comment]
Further investigation: basically key mapping isn't working except for `backspace`.

It's behaving as if `RET` and `c` are both not mapped to any function all.

However running `keepass-mode-select` directly on a group would work flawlessly, bringing me into the group as expected.

So my suspicion is that something is stopping [this](https://github.com/ifosch/keepass-mode/blob/c60a5d14ca37f082fec4c767b6e62a3888916647/keepass-mode.el#L83) from working.

**Comment by ykgoon** [comment]
I got it: `evil-mode` is getting in the way. I turned off `evil-mode` for the buffer, everything worked again.

I can't explain why it wasn't a problem a few weeks ago; maybe `evil-mode` got upgraded and has a clash of keybinding.

I dunno elisp well enough to have a solution on top of my head.

**Comment by ykgoon** [comment]
When running `evil-mode` I need to go into editing-mode in order to operate as usual.

It's not ideal but it's not quite a bug either. Let's close it for now.
